name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v4

    - name: Ustaw Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Zainstaluj zależności
      run: |
        pip install -r requirements.txt
        
    - name: flake8 (styl kodu)
      run: |
        pip install flake8
        flake8 . --exit-zero

    
    - name: Uruchom testy
      run: |
        pytest

    - name: Sprawdzenie jakości kodu (flake8)
      run: |
        pip install flake8
        flake8 app.py test_app.py
